## Modified Gram Schmidt via outer products (example)

In [2]:
using LinearAlgebra
A = rand(1.:10.,6,3)
Q=zeros(6,3); R=zeros(3,3);

A1 = copy(A)
R[1,1] = norm(A1[:,1]);
Q[:,1] = A1[:,1]/R[1,1];
for j=2:3
    R[1,j] = dot(Q[:,1],A1[:,j])
end
R

3×3 Array{Float64,2}:
 12.7279  12.4922  9.27096
  0.0      0.0     0.0    
  0.0      0.0     0.0    

In [3]:
Q

6×3 Array{Float64,2}:
 0.392837   0.0  0.0
 0.31427    0.0  0.0
 0.0785674  0.0  0.0
 0.31427    0.0  0.0
 0.157135   0.0  0.0
 0.785674   0.0  0.0

In [4]:
A2 = A1 - Q[:,1]*R[1,:]'

6×3 Array{Float64,2}:
 0.0          -3.90741   -0.641975
 4.44089e-16  -2.92593    2.08642 
 1.11022e-16   9.01852    8.2716  
 4.44089e-16   5.07407   -1.91358 
 2.22045e-16   0.037037   8.54321 
 0.0           0.185185  -2.28395 

In [5]:
R[2,2] = norm(A2[:,2]);
Q[:,2] = A2[:,2]/R[2,2];
for j=3:3
    R[2,j] = dot(Q[:,2],A2[:,j])
end
R

3×3 Array{Float64,2}:
 12.7279  12.4922  9.27096
  0.0     11.4431  5.34691
  0.0      0.0     0.0    

In [6]:
Q

6×3 Array{Float64,2}:
 0.392837   -0.341464    0.0
 0.31427    -0.255694    0.0
 0.0785674   0.788119    0.0
 0.31427     0.443418    0.0
 0.157135    0.00323663  0.0
 0.785674    0.0161831   0.0

In [7]:
A3 = A2 - Q[:,2]*R[2,:]'

6×3 Array{Float64,2}:
 0.0          0.0   1.1838 
 4.44089e-16  0.0   3.45359
 1.11022e-16  0.0   4.05761
 4.44089e-16  0.0  -4.2845 
 2.22045e-16  0.0   8.5259 
 0.0          0.0  -2.37048