In [1]:
using LinearAlgebra

In [12]:
A = rand(1.:9.,4,4)

4×4 Array{Float64,2}:
 9.0  3.0  8.0  1.0
 4.0  2.0  9.0  9.0
 8.0  4.0  3.0  8.0
 7.0  1.0  8.0  2.0

In [7]:
L = zeros(4,4);  U = zeros(4,4);

In [8]:
U[1,:] = A[1,:]
L[:,1] = A[:,1]/U[1,1]
A = A - L[:,1]*U[1,:]'

4×4 Array{Float64,2}:
 0.0   0.0   0.0   0.0
 0.0   1.0  -3.0  -3.0
 0.0  -3.0  -1.0  -1.0
 0.0  -3.0  -3.0   1.0

In [44]:
function luouter(A)
    m = size(A,1)
    Aj = copy(A)
    L = zeros(m,m);  U = zeros(m,m);
    p = zeros(Int,m)
    for j = 1:m
        p[j]=findmax(abs.(Aj[:,j]))[2]
        U[j,:] = Aj[p[j],:]
        L[:,j] = Aj[:,j]/U[j,j]
        Aj -= L[:,j]*U[j,:]'
    end
    return L,U,p
end

luouter (generic function with 1 method)

In [45]:
L,U,p = luouter(A)

([1.25e-13 1.0 0.0 0.0; 0.5 0.0 0.622837 1.0; 1.0 0.0 0.0 0.0; 0.875 -0.833333 1.0 0.0], [8.0 4.0 3.0 8.0; 0.0 3.0 8.0 1.0; 0.0 0.0 12.0417 -4.16667; 0.0 0.0 0.0 7.59516], [3, 1, 4, 2])

In [46]:
L

4×4 Array{Float64,2}:
 1.25e-13   1.0       0.0       0.0
 0.5        0.0       0.622837  1.0
 1.0        0.0       0.0       0.0
 0.875     -0.833333  1.0       0.0

In [47]:
U

4×4 Array{Float64,2}:
 8.0  4.0   3.0      8.0    
 0.0  3.0   8.0      1.0    
 0.0  0.0  12.0417  -4.16667
 0.0  0.0   0.0      7.59516

In [48]:
norm(A-L*U)

1.1102230246251565e-16

In [49]:
L[p,:]

4×4 Array{Float64,2}:
 1.0        0.0       0.0       0.0
 1.25e-13   1.0       0.0       0.0
 0.875     -0.833333  1.0       0.0
 0.5        0.0       0.622837  1.0

In [22]:
A[1,1] = 0

0

In [23]:
A

4×4 Array{Float64,2}:
 0.0  3.0  8.0  1.0
 4.0  2.0  9.0  9.0
 8.0  4.0  3.0  8.0
 7.0  1.0  8.0  2.0

In [24]:
L,U = luouter(A)

([NaN NaN NaN NaN; Inf NaN NaN NaN; Inf NaN NaN NaN; Inf NaN NaN NaN], [0.0 3.0 8.0 1.0; NaN -Inf -Inf -Inf; NaN NaN NaN NaN; NaN NaN NaN NaN])

In [25]:
A[1,1] = 1e-12

1.0e-12

In [26]:
L,U=luouter(A)

([1.0 -0.0 -0.0 -0.0; 4.0e12 1.0 -0.0 -0.0; 8.0e12 2.0 1.0 -0.0; 7.0e12 1.75 0.0723958 1.0], [1.0e-12 3.0 8.0 1.0; 0.0 -1.2e13 -3.2e13 -4.0e12; 0.0 0.0 -15.0 -10.0; 0.0 0.0 0.0 -12.193])

In [27]:
L

4×4 Array{Float64,2}:
 1.0     -0.0   -0.0        -0.0
 4.0e12   1.0   -0.0        -0.0
 8.0e12   2.0    1.0        -0.0
 7.0e12   1.75   0.0723958   1.0

In [28]:
U

4×4 Array{Float64,2}:
 1.0e-12   3.0       8.0       1.0   
 0.0      -1.2e13   -3.2e13   -4.0e12
 0.0       0.0     -15.0     -10.0   
 0.0       0.0       0.0     -12.193 

In [29]:
norm(A-L*U)

0.001067877792894525

In [30]:
cond(A)

7.783999809844254

In [31]:
A

4×4 Array{Float64,2}:
 1.0e-12  3.0  8.0  1.0
 4.0      2.0  9.0  9.0
 8.0      4.0  3.0  8.0
 7.0      1.0  8.0  2.0

In [33]:
findmax(abs.(A[:,1]))[2]

3

In [34]:
p=zeros(Int,4)

4-element Array{Int64,1}:
 0
 0
 0
 0

In [36]:
p[1]=findmax(abs.(A[:,1]))[2]

3

In [40]:
Aj=copy(A);

In [41]:
U[1,:] = Aj[p[1],:]
L[:,1] = Aj[:,1]/U[1,1]
Aj = Aj - L[:,1]*U[1,:]'

4×4 Array{Float64,2}:
 0.0   3.0  8.0     1.0
 0.0   0.0  7.5     5.0
 0.0   0.0  0.0     0.0
 0.0  -2.5  5.375  -5.0

In [42]:
p[2]=findmax(abs.(Aj[:,2]))[2]

1

In [43]:
U[2,:] = Aj[p[2],:]
L[:,2] = Aj[:,2]/U[2,2]
Aj = Aj - L[:,2]*U[2,:]'

4×4 Array{Float64,2}:
 0.0  0.0   0.0      0.0    
 0.0  0.0   7.5      5.0    
 0.0  0.0   0.0      0.0    
 0.0  0.0  12.0417  -4.16667

In [50]:
function luouter(A)
    m = size(A,1)
    Aj = copy(A)
    L = zeros(m,m);  U = zeros(m,m);
    p = zeros(Int,m)
    for j = 1:m
        p[j]=findmax(abs.(Aj[:,j]))[2]
        U[j,:] = Aj[p[j],:]
        L[:,j] = Aj[:,j]/U[j,j]
        Aj -= L[:,j]*U[j,:]'
    end
    return L,U,p
end

luouter (generic function with 1 method)

In [51]:
L,U,p = luouter(A)

([1.25e-13 1.0 0.0 0.0; 0.5 0.0 0.622837 1.0; 1.0 0.0 0.0 0.0; 0.875 -0.833333 1.0 0.0], [8.0 4.0 3.0 8.0; 0.0 3.0 8.0 1.0; 0.0 0.0 12.0417 -4.16667; 0.0 0.0 0.0 7.59516], [3, 1, 4, 2])

In [52]:
L

4×4 Array{Float64,2}:
 1.25e-13   1.0       0.0       0.0
 0.5        0.0       0.622837  1.0
 1.0        0.0       0.0       0.0
 0.875     -0.833333  1.0       0.0

In [53]:
U

4×4 Array{Float64,2}:
 8.0  4.0   3.0      8.0    
 0.0  3.0   8.0      1.0    
 0.0  0.0  12.0417  -4.16667
 0.0  0.0   0.0      7.59516

$A = (P^TL) U$

$PA=LU$

In [55]:
LL,UU,pp=lu(A)

LU{Float64,Array{Float64,2}}
L factor:
4×4 Array{Float64,2}:
 1.0        0.0       0.0       0.0
 1.25e-13   1.0       0.0       0.0
 0.875     -0.833333  1.0       0.0
 0.5        0.0       0.622837  1.0
U factor:
4×4 Array{Float64,2}:
 8.0  4.0   3.0      8.0    
 0.0  3.0   8.0      1.0    
 0.0  0.0  12.0417  -4.16667
 0.0  0.0   0.0      7.59516

In [56]:
pp

4-element Array{Int64,1}:
 3
 1
 4
 2

In [57]:
m = 8
A = tril(-ones(m,m))
A[1:m+1:end] .= 1
A[:,m] .= 1
A

8×8 Array{Float64,2}:
  1.0   0.0   0.0   0.0   0.0   0.0   0.0  1.0
 -1.0   1.0   0.0   0.0   0.0   0.0   0.0  1.0
 -1.0  -1.0   1.0   0.0   0.0   0.0   0.0  1.0
 -1.0  -1.0  -1.0   1.0   0.0   0.0   0.0  1.0
 -1.0  -1.0  -1.0  -1.0   1.0   0.0   0.0  1.0
 -1.0  -1.0  -1.0  -1.0  -1.0   1.0   0.0  1.0
 -1.0  -1.0  -1.0  -1.0  -1.0  -1.0   1.0  1.0
 -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  1.0

In [58]:
L,U,p=lu(A)

LU{Float64,Array{Float64,2}}
L factor:
8×8 Array{Float64,2}:
  1.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
 -1.0   1.0   0.0   0.0   0.0   0.0   0.0  0.0
 -1.0  -1.0   1.0   0.0   0.0   0.0   0.0  0.0
 -1.0  -1.0  -1.0   1.0   0.0   0.0   0.0  0.0
 -1.0  -1.0  -1.0  -1.0   1.0   0.0   0.0  0.0
 -1.0  -1.0  -1.0  -1.0  -1.0   1.0   0.0  0.0
 -1.0  -1.0  -1.0  -1.0  -1.0  -1.0   1.0  0.0
 -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0  1.0
U factor:
8×8 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0    1.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0    2.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0    4.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0    8.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0   16.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0   32.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0   64.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  128.0

In [59]:
p

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

In [63]:
m = 60
A = tril(-ones(m,m))
A[1:m+1:end] .= 1
A[:,m] .= 1
xact = rand(m)
b = A*xact
norm( xact - A\b )/ norm(xact)


0.22303240146572065

In [61]:
cond(A)

22.755451813074632

In [65]:
L,U=lu(A)
norm(U)

6.656395410392714e17